In [513]:
import pandas as pd

In [514]:
print("this is new to learn here. ")

this is new to learn here.

In [515]:
obesityDataSet = pd.read_csv("./obesity_prediction.csv")

In [516]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [517]:
obesityDataSet.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [518]:
obesityDataSet.head(4)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I

In [519]:
obesityDataSet.tail(11)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2100,Female,25.777565,1.628205,107.378702,yes,yes,3.0,3.0,Sometimes,no,2.506631,no,0.025787,0.484165,Sometimes,Public_Transportation,Obesity_Type_III
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [520]:
obesityDataSet.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
983,Male,29.956198,1.703688,82.207978,yes,yes,2.119643,3.292956,Sometimes,no,1.723372,no,0.0,0.987102,Sometimes,Automobile,Overweight_Level_II

In [521]:
obesityDataSet.sample(5)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2048,Female,18.634286,1.669354,126.088301,yes,yes,3.0,3.0,Sometimes,no,1.144539,no,0.922014,0.899673,Sometimes,Public_Transportation,Obesity_Type_III
109,Female,21.000000,1.650000,88.000000,yes,yes,3.0,1.0,Sometimes,no,3.000000,no,2.000000,1.000000,no,Public_Transportation,Obesity_Type_I
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1986,Female,21.210732,1.716497,130.871127,yes,yes,3.0,3.0,Sometimes,no,1.301657,no,1.718543,0.947884,Sometimes,Public_Transportation,Obesity_Type_III
1869,Female,26.000000,1.621245,111.267334,yes,yes,3.0,3.0,Sometimes,no,2.605685,no,0.000000,0.199227,Sometimes,Public_Transportation,Obesity_Type_III

In [522]:
obesityDataSet.sample(11, random_state=11)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
22,Female,22.000000,1.650000,60.000000,yes,yes,3.000000,3.000000,Sometimes,no,2.000000,no,1.000000,0.000000,Sometimes,Automobile,Normal_Weight
1405,Male,23.324710,1.769484,96.078462,yes,yes,2.000000,3.000000,Sometimes,no,3.000000,no,3.000000,2.000000,no,Public_Transportation,Obesity_Type_I
932,Male,22.828435,1.710415,75.142858,yes,yes,2.786008,3.000000,Sometimes,no,2.526193,no,0.925118,2.000000,Sometimes,Public_Transportation,Overweight_Level_I
501,Female,21.853826,1.755643,137.796884,yes,yes,3.000000,3.000000,Sometimes,no,2.184707,no,1.978631,0.838957,Sometimes,Public_Transportation,Obesity_Type_III
1097,Female,34.044229,1.665807,77.098973,yes,yes,2.976975,1.346987,Sometimes,no,1.868349,no,0.702538,0.879333,no,Automobile,Overweight_Level_II
1197,Male,33.151905,1.685127,83.986895,yes,yes,2.000000,2.473911,Sometimes,no,2.452789,no,0.932792,0.000000,no,Automobile,Overweight_Level_II
896,Male,21.008290,1.621412,70.000000,no,yes,2.000000,1.000000,no,no,2.795651,no,0.808730,0.000000,Sometimes,Public_Transportation,Overweight_Level_I
1256,Male,18.000000,1.791174,108.960600,yes,yes,2.000000,1.086870,Sometimes,no,2.279124,no,1.000000,1.609773,no,Public_Transportation,Obesity_Type_I
819,Male,23.170309,1.707557,75.306702,yes,yes,2.303367,3.042774,Sometimes,no,1.277636,no,0.944982,0.366126,Sometimes,Public_Transportation,Overweight_Level_I
1522,Male,28.363149,1.793476,112.725005,yes,yes,1.991240,3.000000,Sometimes,no,2.000000,no,0.000000,0.292956,Sometimes,Public_Transportation,Obesity_Type_II
1365,Female,18.011903,1.650000,84.210535,yes,yes,2.859160,3.000000,Sometimes,no,1.000000,no,1.020525,0.786066,no,Public_Transportation,Obesity_Type_I

In [523]:
obesityDataSet.sample(11 , random_state=10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2054,Female,21.008297,1.723587,131.929712,yes,yes,3.000000,3.000000,Sometimes,no,1.683448,no,1.645532,0.858059,Sometimes,Public_Transportation,Obesity_Type_III
1152,Male,22.988004,1.808270,91.363293,yes,yes,1.963965,1.836226,Sometimes,no,1.855370,no,0.000000,1.667745,Sometimes,Public_Transportation,Overweight_Level_II
1883,Female,26.000000,1.631332,111.829957,yes,yes,3.000000,3.000000,Sometimes,no,2.559750,no,0.000000,0.237307,Sometimes,Public_Transportation,Obesity_Type_III
248,Male,21.000000,1.720000,72.000000,yes,yes,3.000000,3.000000,Always,no,3.000000,yes,3.000000,0.000000,Sometimes,Automobile,Normal_Weight
375,Male,41.000000,1.800000,92.000000,yes,yes,2.000000,1.000000,Frequently,no,3.000000,no,1.000000,0.000000,Sometimes,Automobile,Overweight_Level_II
589,Female,19.948140,1.530884,39.371523,no,yes,1.522001,3.000000,Sometimes,no,1.981260,no,2.306844,0.720454,Sometimes,Public_Transportation,Insufficient_Weight
1373,Male,26.032416,1.824432,105.131956,yes,yes,3.000000,3.000000,Sometimes,no,2.110611,no,1.890907,1.584830,Sometimes,Public_Transportation,Obesity_Type_I
370,Male,19.000000,1.800000,60.000000,no,yes,2.000000,3.000000,Sometimes,no,1.000000,no,1.000000,1.000000,no,Public_Transportation,Normal_Weight
145,Male,21.000000,1.620000,70.000000,no,yes,2.000000,1.000000,no,no,3.000000,no,1.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_I
1703,Male,22.580038,1.849507,121.560938,yes,yes,3.000000,2.272801,Sometimes,no,1.560064,no,0.796770,0.000000,Sometimes,Public_Transportation,Obesity_Type_II
1455,Female,18.000000,1.692242,90.019501,yes,yes,2.642744,3.000000,Sometimes,no,1.904054,no,1.645654,0.363549,Sometimes,Public_Transportation,Obesity_Type_I

In [524]:
obesityDataSet.sample(3 , random_state=299)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
1133,Male,34.098174,1.841151,91.798103,yes,yes,2.0,2.997414,Sometimes,no,1.259454,no,0.935217,0.997600,Sometimes,Automobile,Overweight_Level_II
839,Male,19.789291,1.820643,85.000000,yes,yes,3.0,3.000000,Sometimes,no,2.759246,no,1.763277,0.453314,Sometimes,Public_Transportation,Overweight_Level_I
657,Female,19.052833,1.546551,42.069992,no,yes,3.0,1.735493,Sometimes,no,2.318736,no,1.193486,0.745680,no,Public_Transportation,Insufficient_Weight

In [525]:
obesityDataSet.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history', 'FAVC', 'FCVC',
       'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS',
       'Obesity'],
      dtype='object')

In [526]:
obesityDataSet.columns.to_list()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [527]:
obesityDataSet.index

RangeIndex(start=0, stop=2111, step=1)

In [528]:
list(obesityDataSet.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [529]:
# for getting no of rows n no of cols  
obesityDataSet.shape

(2111, 17)

In [530]:
# update data 

# checking data at location n update it  later 
obesityDataSet.loc[1,'Age']

np.float64(21.0)

In [531]:
obesityDataSet.loc[1,'Age'] = "Adding Updated String at the position of int"

C:\Users\satyansh pandey\AppData\Local\Temp\ipykernel_16764\2807611631.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Adding Updated String at the position of int' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  obesityDataSet.loc[1,'Age'] = "Adding Updated String at the position of int"

In [532]:
# printing or accessig updated data from csv 
obesityDataSet.loc[1,'Age']

'Adding Updated String at the position of int'

In [533]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,Adding Updated String at the position of int,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [534]:
# again updating and making it into int 
obesityDataSet.loc[1,'Age'] = 1000

In [535]:
# again checking after update 
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,1000,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [536]:
obesityDataSet.loc[: , 'SMOKE']='Yes'

In [537]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,1000,1.52,56.0,yes,no,3.0,3.0,Sometimes,Yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,Yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,Yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [538]:
obesityDataSet.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,Yes,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,Yes,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,Yes,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,Yes,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,Yes,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [539]:
obesityDataSet.loc[0 , 'Height'] = 99

In [540]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,1000,1.52,56.0,yes,no,3.0,3.0,Sometimes,Yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,Yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,Yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [541]:
obesityDataSet.loc[1:4 , 'SMOKE'] = "MayBe"

In [542]:
obesityDataSet.head(8)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,1000,1.52,56.0,yes,no,3.0,3.0,Sometimes,MayBe,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,MayBe,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,MayBe,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,MayBe,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,Yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,Yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,Yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight

In [543]:




# creatting function n applying into any column to do some modification 

def increment_age_by_5(x):
    return x+100
obesityDataSet['Age'] = obesityDataSet['Age'].apply(increment_age_by_5)

obesityDataSet['Age']

0        121.000000
1       1100.000000
2        123.000000
3        127.000000
4        122.000000
           ...
2106     120.976842
2107     121.982942
2108     122.524036
2109     124.361936
2110     123.664709
Name: Age, Length: 2111, dtype: float64

In [544]:
# subtracting age by 5 
def subtractingAgeBy5(x):
    print(x,end=" . ")
    return x-10

obesityDataSet['Age'] = obesityDataSet['Age'].apply(subtractingAgeBy5)
obesityDataSet['Age']

121.0 . 1100.0 . 123.0 . 127.0 . 122.0 . 129.0 . 123.0 . 122.0 . 124.0 . 122.0 . 126.0 . 121.0 . 122.0 . 141.0 . 123.0 . 122.0 . 127.0 . 129.0 . 130.0 . 123.0 . 122.0 . 152.0 . 122.0 . 122.0 . 121.0 . 120.0 . 121.0 . 123.0 . 119.0 . 123.0 . 129.0 . 131.0 . 124.0 . 139.0 . 122.0 . 121.0 . 122.0 . 121.0 . 123.0 . 121.0 . 121.0 . 123.0 . 121.0 . 121.0 . 121.0 . 121.0 . 121.0 . 121.0 . 120.0 . 121.0 . 121.0 . 120.0 . 123.0 . 123.0 . 122.0 . 123.0 . 122.0 . 121.0 . 117.0 . 120.0 . 121.0 . 120.0 . 122.0 . 122.0 . 121.0 . 121.0 . 123.0 . 123.0 . 130.0 . 123.0 . 123.0 . 122.0 . 124.0 . 119.0 . 124.0 . 123.0 . 124.0 . 124.0 . 123.0 . 123.0 . 119.0 . 130.0 . 123.0 . 119.0 . 125.0 . 123.0 . 121.0 . 119.0 . 122.0 . 129.0 . 125.0 . 120.0 . 155.0 . 120.0 . 124.0 . 126.0 . 123.0 . 121.0 . 121.0 . 123.0 . 121.0 . 122.0 . 121.0 . 122.0 . 138.0 . 125.0 . 125.0 . 122.0 . 122.0 . 121.0 . 121.0 . 122.0 . 118.0 . 122.0 . 119.0 . 117.0 . 115.0 . 117.0 . 123.0 . 119.0 . 123.0 . 123.0 . 121.0 . 124.0 . 123.0 . 118.0 . 119.0 . 119.0 . 120.0 . 127.0 . 120.0 . 123.0 . 119.0 . 161.0 . 130.0 . 124.0 . 125.0 . 144.0 . 131.0 . 125.0 . 123.0 . 125.0 . 123.0 . 134.0 . 122.0 . 121.0 . 124.0 . 136.0 . 127.0 . 132.0 . 125.0 . 130.0 . 138.0 . 134.0 . 122.0 . 131.0 . 135.0 . 121.0 . 140.0 . 127.0 . 120.0 . 155.0 . 121.0 . 125.0 . 135.0 . 130.0 . 129.0 . 120.0 . 122.0 . 145.0 . 122.0 . 118.0 . 123.0 . 118.0 . 121.0 . 138.0 . 118.0 . 122.0 . 126.0 . 121.0 . 118.0 . 123.0 . 122.0 . 123.0 . 121.0 . 131.0 . 139.0 . 125.0 . 135.0 . 133.0 . 120.0 . 126.0 . 120.0 . 120.0 . 123.0 . 119.0 . 122.0 . 141.0 . 118.0 . 123.0 . 123.0 . 141.0 . 126.0 . 129.0 . 127.0 . 123.0 . 119.0 . 130.0 . 122.0 . 122.0 . 120.0 . 121.0 . 124.0 . 121.0 . 121.0 . 121.0 . 123.0 . 121.0 . 121.0 . 121.0 . 121.0 . 123.0 . 121.0 . 122.0 . 123.0 . 125.0 . 120.0 . 124.0 . 140.0 . 132.0 . 120.0 . 121.0 . 151.0 . 134.0 . 119.0 . 119.0 . 121.0 . 119.0 . 120.0 . 119.0 . 117.0 . 122.0 . 120.0 . 133.0 . 121.0 . 120.0 . 120.0 . 120.0 . 121.0 . 121.0 . 120.0 . 120.0 . 156.0 . 126.0 . 122.0 . 119.0 . 118.0 . 119.0 . 118.0 . 118.0 . 121.0 . 128.0 . 118.0 . 123.0 . 118.0 . 118.0 . 139.0 . 138.0 . 117.0 . 123.0 . 123.0 . 119.0 . 118.0 . 125.0 . 125.0 . 118.0 . 116.0 . 121.0 . 132.0 . 118.0 . 121.0 . 118.0 . 118.0 . 117.0 . 120.0 . 121.0 . 121.0 . 118.0 . 117.0 . 119.0 . 116.0 . 117.0 . 121.0 . 119.0 . 118.0 . 116.0 . 121.0 . 126.0 . 118.0 . 123.0 . 126.0 . 118.0 . 116.0 . 116.0 . 120.0 . 123.0 . 124.0 . 123.0 . 120.0 . 116.0 . 117.0 . 117.0 . 116.0 . 117.0 . 126.0 . 126.0 . 138.0 . 118.0 . 125.0 . 127.0 . 121.0 . 138.0 . 123.0 . 118.0 . 130.0 . 121.0 . 118.0 . 123.0 . 119.0 . 119.0 . 117.0 . 117.0 . 127.0 . 123.0 . 118.0 . 119.0 . 120.0 . 118.0 . 117.0 . 119.0 . 121.0 . 120.0 . 123.0 . 123.0 . 118.0 . 117.0 . 121.0 . 117.0 . 118.0 . 120.0 . 117.0 . 126.0 . 117.0 . 124.0 . 117.0 . 127.0 . 117.0 . 117.0 . 141.0 . 133.0 . 120.0 . 140.0 . 137.0 . 119.0 . 124.0 . 124.0 . 133.0 . 140.0 . 137.0 . 120.0 . 119.0 . 117.0 . 118.0 . 121.0 . 118.0 . 141.0 . 136.0 . 118.0 . 118.0 . 117.0 . 125.0 . 121.0 . 129.0 . 117.0 . 118.0 . 116.0 . 118.0 . 137.0 . 118.0 . 116.0 . 123.0 . 118.0 . 118.0 . 118.0 . 117.0 . 120.0 . 138.0 . 120.0 . 121.0 . 121.0 . 118.0 . 126.0 . 127.0 . 126.0 . 134.0 . 118.0 . 133.0 . 119.0 . 120.0 . 133.0 . 120.0 . 120.0 . 133.0 . 133.0 . 133.0 . 114.0 . 134.0 . 118.0 . 118.0 . 129.0 . 118.0 . 118.0 . 119.0 . 133.0 . 133.0 . 119.0 . 122.0 . 120.0 . 123.0 . 126.0 . 118.0 . 118.0 . 119.0 . 118.0 . 119.0 . 119.0 . 118.0 . 118.0 . 119.0 . 119.0 . 118.0 . 118.0 . 126.0 . 118.0 . 119.0 . 119.0 . 119.0 . 119.0 . 124.0 . 118.0 . 119.0 . 119.0 . 123.0 . 118.0 . 120.0 . 118.0 . 133.0 . 119.0 . 119.0 . 119.0 . 118.0 . 121.0 . 127.0 . 117.0 . 118.0 . 118.0 . 122.0 . 122.0 . 120.0 . 119.0 . 120.0 . 118.0 . 118.0 . 118.0 . 119.0 . 118.0 . 118.0 . 118.0 . 119.0 . 117.0 . 118.0 . 118.0 . 120.0 . 118.0 . 136.0 . 121.0 . 123.0 . 120.0 . 121.0 . 119.0 . 124.0 . 125.0 . 145.0 . 120.0 . 118.0 . 119.0 . 118.0 . 120.0 . 125.196214 . 118.503343 . 126.0 . 121.853826 . 121.90012 . 118.306615 . 126.0 . 126.0 . 121.849705 . 119.799054 . 117.188754 . 122.28502399999999 . 122.0 . 121.02497 . 122.038327 . 121.243142 . 122.142432 . 121.962426 . 121.491055 . 122.717943 . 123.501249 . 118.535075 . 119.0 . 119.0 . 120.254534 . 121.0 . 120.225396 . 119.86997 . 120.147114 . 121.0 . 121.996523 . 121.376426 . 119.724106 . 123.0 . 122.851834 . 123.0 . 118.216032 . 121.81119 . 118.164768 . 118.871794 . 118.766033 . 118.540535 . 119.88036 . 119.717249 . 119.633898 . 123.0 . 120.406871 . 123.0 . 119.058511 . 118.827008 . 119.314964 . 129.970445 . 132.383858 . 124.163526 . 117.038222 . 116.30687 . 116.198153 . 118.0 . 118.0 . 118.0 . 117.486869 . 119.920629 . 118.426619 . 117.082867 . 117.000433 . 116.270434 . 117.908114 . 117.120699 . 119.329542 . 122.377998 . 120.954955 . 122.991668 . 119.300435 . 117.065445 . 119.084967 . 118.02485300000001 . 119.833682 . 117.767432 . 119.504696 . 119.950605 . 119.0 . 117.0 . 117.0 . 118.525525 . 122.92635200000001 . 121.78535099999999 . 123.0 . 117.402028 . 118.0 . 118.48207 . 118.53084 . 119.94814 . 120.400053 . 119.556729 . 117.70367999999999 . 118.274358 . 118.0 . 117.210933 . 117.46941699999999 . 118.0 . 118.0 . 118.0 . 119.010211 . 119.091346 . 119.773303 . 119.483036 . 119.0 . 119.40720400000001 . 118.0 . 118.424941 . 118.0 . 119.97981 . 121.798856 . 122.209706 . 123.018443 . 119.376997 . 120.971429 . 120.345161 . 120.519916 . 120.406066 . 121.478496 . 118.372563 . 119.931667 . 122.998709 . 118.006742 . 134.799519 . 116.496978 . 118.0 . 117.37713099999999 . 116.61183700000001 . 117.080493 . 122.970655 . 117.764764 . 119.272573 . 119.0 . 117.06712999999999 . 123.0 . 118.0 . 119.054008 . 118.0 . 117.491272 . 118.0 . 120.172661 . 119.220108 . 118.0 . 119.96247 . 117.58062699999999 . 121.12509800000001 . 122.033129 . 120.744839 . 122.547298 . 121.837996 . 123.035829 . 121.529439 . 121.287999 . 123.444286 . 122.329041 . 118.91505000000001 . 119.0 . 119.05283299999999 . 119.59904 . 121.0 . 119.673262 . 120.244359 . 120.552695 . 121.0 . 121.997683 . 121.274628 . 118.90943899999999 . 122.396504 . 119.084317 . 121.084625 . 118.06876700000001 . 121.813083 . 118.038422 . 118.874591 . 119.21164 . 118.988581 . 119.408999 . 119.665881 . 119.758286 . 122.422674 . 120.242237 . 122.637018 . 119.007177 . 118.288205 . 119.314429 . 127.14823 . 125.380557 . 122.867719 . 117.729923 . 116.834813 . 117.521754 . 118.0 . 118.0 . 118.128249 . 117.405104 . 119.72925000000001 . 118.525834 . 118.595614 . 116.613108 . 116.928791 . 117.758315 . 117.282945 . 119.993154 . 122.93561199999999 . 120.738469 . 122.99368 . 119.317148 . 116.910997 . 119.071027 . 118.019572 . 119.735968 . 118.094079 . 119.05493799999999 . 120.850119 . 119.34925799999999 . 117.0 . 117.203917 . 117.671064 . 121.310907 . 121.708354 . 122.176922 . 117.823438 . 118.0 . 118.281092 . 118.656912 . 119.994543 . 120.255616 . 119.865895 . 117.88807299999999 . 118.470562 . 117.92549700000001 . 117.000752 . 117.362129 . 118.0 . 118.0 . 118.0 . 119.029494 . 119.269079 . 119.94624400000001 . 119.639431 . 119.0 . 119.434709 . 118.0 . 118.381382 . 118.0 . 126.69857999999999 . 121.12583599999999 . 125.191627 . 121.963457 . 121.0 . 119.114981 . 141.823567 . 121.142432 . 121.962426 . 118.836315 . 123.572648 . 133.700749 . 121.84502499999999 . 121.0 . 135.125401 . 136.769646 . 121.868932 . 122.549208 . 121.0 . 121.0 . 130.958957 . 121.017383 . 119.623574 . 119.637947 . 121.413642 . 121.029633 . 122.667596 . 120.0 . 121.81119 . 121.0 . 118.128206 . 121.0 . 129.08107 . 126.358919 . 122.717249 . 119.816949 . 124.023972 . 132.593129 . 123.0 . 116.941489 . 116.172992 . 123.71259 . 135.194089 . 123.172982 . 137.218161 . 119.076443 . 116.30687 . 118.297229 . 118.610761 . 117.451085 . 129.740496 . 131.539393 . 118.026457 . 119.47554 . 119.0 . 118.0 . 118.270434 . 119.816228 . 128.39124 . 126.758516 . 121.033794 . 122.429812 . 126.650419 . 121.618246 . 121.012542 . 121.071195 . 119.741202 . 119.21638 . 142.24475 . 122.28308200000001 . 121.086512 . 123.451595 . 122.740275 . 118.90025299999999 . 123.170309 . 132.997118 . 132.501143 . 121.938831 . 121.90953400000001 . 121.0 . 137.455752 . 140.0 . 138.943282 . 121.987341 . 121.198217 . 121.0 . 121.0 . 121.0 . 121.0 . 121.0 . 129.32038 . 131.255587 . 122.85177300000001 . 126.0 . 119.78929099999999 . 119.895877 . 119.693804 . 119.226314 . 121.652229 . 121.687409 . 121.45546300000001 . 121.0 . 121.0 . 119.33740399999999 . 121.701643 . 121.620245 . 121.012569 . 121.016623 . 119.0 . 121.0 . 121.0 . 127.899784 . 128.825223 . 126.047077 . 123.0 . 120.0 . 121.832995 . 130.255744 . 130.613586 . 123.245408 . 118.0 . 118.0 . 116.95049900000001 . 121.837058 . 127.0 . 135.483601 . 123.801436 . 123.367212 . 140.0 . 116.38009 . 116.865984 . 116.093234 . 118.0 . 118.83919 . 119.726522 . 118.947102 . 117.781183 . 133.100581 . 133.251015 . 118.985119 . 118.871917 . 119.478533 . 119.429723 . 120.979254 . 118.869151 . 118.236087 . 120.901393 . 117.08525 . 125.78592499999999 . 126.787842 . 121.037514 . 121.00829 . 126.70371 . 121.731497 . 121.052894 . 121.0 . 119.241058 . 138.939448 . 139.965474 . 120.261925 . 120.31094 . 121.420537 . 118.845518 . 123.562135 . 123.118327 . 133.732714 . 121.571288 . 121.16557399999999 . 121.0 . 121.0 . 138.692265 . 138.952866 . 136.63145600000001 . 121.996118 . 121.951309 . 122.018228 . 121.0 . 121.0 . 121.0 . 129.934465 . 131.166572 . 120.534606 . 119.97166 . 119.627 . 121.92938699999999 . 121.00943699999999 . 121.538225 . 122.828435 . 122.814657 . 119.576682 . 121.81465299999999 . 121.979769 . 121.0 . 121.02850000000001 . 118.721041 . 121.0 . 121.0 . 129.463168 . 124.284861 . 126.288417 . 123.455324 . 119.637203 . 122.239836 . 131.62638 . 123.0 . 122.874658 . 117.420269 . 117.807828 . 116.240576 . 123.25245699999999 . 134.772902 . 122.766227 . 139.214514 . 119.85897299999999 . 116.370009 . 117.992717 . 119.17993200000001 . 119.621545 . 119.755797 . 117.09901500000001 . 117.25813 . 129.153907 . 132.278869 . 131.793937 . 118.014333 . 119.685 . 119.506389 . 119.0 . 118.0 . 118.003153 . 118.05239399999999 . 119.774317 . 121.180346 . 121.793724 . 120.880161 . 121.18354 . 132.774488 . 131.327609 . 129.956198 . 121.40342100000001 . 122.59143900000001 . 128.583944 . 138.825189 . 135.217173 . 120.392665 . 122.154854 . 119.108796 . 120.70768 . 120.634694 . 122.052152 . 122.869778 . 122.909992 . 123.0 . 124.679807 . 123.884212 . 125.461411 . 131.333798 . 124.108711 . 128.830558 . 117.570089 . 119.027574 . 125.632447 . 122.94313 . 123.285553 . 123.0 . 125.19291 . 134.389906 . 126.595893 . 155.24625 . 134.543563 . 121.808159 . 118.118277 . 142.189023 . 122.0 . 128.770852 . 125.48338100000001 . 121.67314999999999 . 123.469538 . 123.0 . 123.0 . 138.464538 . 137.496175 . 133.690239 . 134.369686 . 131.426573 . 134.288249 . 118.86387500000001 . 118.951144 . 119.671876 . 150.832559 . 117.971574 . 118.0 . 118.70176599999999 . 134.389679 . 117.178483 . 133.0816 . 133.270448 . 136.310292 . 120.0 . 118.549437 . 134.243146 . 123.32012 . 119.703095 . 119.223259 . 129.695603 . 127.0 . 121.02766199999999 . 133.01525800000002 . 118.0 . 130.553097 . 133.0 . 124.91199399999999 . 124.444846 . 119.911246 . 134.204408 . 134.281681 . 123.38437400000001 . 143.238402 . 145.0 . 122.087389 . 121.378039 . 131.398281 . 131.484494 . 121.709159 . 130.711381 . 134.821442 . 120.843363 . 119.443639 . 120.492077 . 122.944349 . 123.0 . 124.06894 . 123.728707 . 129.216019 . 124.751511 . 128.977792 . 117.441593 . 119.12614500000001 . 124.122589 . 123.0 . 128.824194 . 134.204611 . 128.167799 . 155.137881 . 134.970367 . 120.986834 . 138.37805600000002 . 122.18881 . 121.082384 . 125.29320200000001 . 123.0 . 139.170029 . 134.044229 . 133.182127 . 119.821996 . 119.149706 . 146.491859 . 117.894784 . 118.88485 . 138.384177 . 122.675679 . 133.049121 . 137.205173 . 119.027417 . 137.492444 . 124.65759800000001 . 118.011718 . 127.349745 . 118.0 . 133.009285 . 118.0 . 130.079371 . 125.035915 . 118.198322 . 135.456326 . 123.806789 . 139.392569 . 121.384259 . 122.730414 . 121.20563 . 121.333429 . 132.787101 . 132.610018 . 130.022598 . 121.123048 . 122.989846 . 124.320154 . 137.275298 . 134.098174 . 121.001282 . 121.95994 . 119.795269 . 119.090023 . 120.820455 . 122.087056 . 122.185756 . 122.980957 . 123.0 . 124.190896 . 123.94003000000001 . 126.591628 . 131.264628 . 123.629159 . 126.208134 . 117.68905699999999 . 119.16096999999999 . 125.45763 . 122.988004 . 123.603191 . 122.882558 . 123.58605800000001 . 134.432669 . 125.472995 . 155.022494 . 134.647036 . 121.99733499999999 . 118.181821 . 141.743333 . 121.473078 . 127.757187 . 125.11353700000001 . 121.82165 . 120.670975 . 122.649792 . 123.154311 . 138.097395 . 137.642177 . 134.176795 . 134.231083 . 131.965402 . 133.185661 . 118.741188 . 119.955257 . 119.684891 . 147.7061 . 117.99700899999999 . 117.97178600000001 . 120.432717 . 133.954433 . 117.039058 . 133.070142 . 134.993835 . 135.719457 . 119.005725 . 118.850466 . 131.540751 . 123.335391 . 119.749627 . 119.565496 . 130.357745 . 127.0 . 121.380336 . 133.151905 . 118.0 . 132.241587 . 131.662814 . 124.347414 . 124.362124 . 119.46271300000001 . 135.432059 . 133.864257 . 123.807181 . 139.585811 . 145.821267 . 125.929746 . 126.042738 . 130.551762 . 139.75957499999998 . 131.386405 . 125.70628500000001 . 143.60490099999998 . 142.31607 . 122.654316 . 122.679935 . 124.07952399999999 . 121.196152 . 122.596576 . 123.0 . 137.356288 . 122.75464600000001 . 123.252906 . 122.02543800000001 . 118.086772 . 125.994393 . 140.821515 . 123.0 . 137.955371 . 131.315593 . 122.661556 . 140.317787 . 123.365649 . 121.72127 . 135.389491 . 122.06146100000001 . 123.0 . 123.0 . 140.951591 . 139.135634 . 126.271621 . 123.779235 . 120.586978 . 121.669478 . 123.0 . 120.825962 . 118.178023 . 118.0 . 118.267696 . 123.0 . 123.0 . 120.9859 . 121.504943 . 118.0 . 118.0 . 119.442663 . 122.86501799999999 . 121.948577 . 121.214617 . 122.277859 . 137.83294899999999 . 137.631769 . 117.6739 . 137.524551 . 143.510672 . 118.0 . 118.0 . 129.506287 . 118.0 . 124.733308 . 129.0 . 118.0 . 121.098035 . 119.089595 . 118.312665 . 118.260079 . 126.004294 . 125.99474599999999 . 136.726617 . 138.297259 . 130.163408 . 128.770039 . 142.337283 . 147.283374 . 122.518787 . 122.836315 . 123.0 . 122.975526 . 122.720449 . 123.887569 . 123.0 . 123.0 . 138.148845 . 137.96543 . 122.771612 . 122.582371 . 121.008051 . 122.591026 . 116.129279 . 116.913841 . 129.43879 . 129.881301 . 143.591999 . 140.993179 . 122.936098 . 123.0 . 137.597953 . 137.532066 . 131.630054 . 131.64108099999999 . 121.872484 . 121.83489399999999 . 136.02397200000001 . 139.65655900000002 . 124.184891 . 123.237302 . 135.322112 . 131.387982 . 123.0 . 123.0 . 122.67945399999999 . 122.480889 . 141.403862 . 140.70277099999998 . 129.389239 . 130.967417 . 123.474165 . 124.317607 . 117.052914 . 118.04892 . 122.875223 . 122.884722 . 118.729566 . 121.011124 . 118.603496 . 121.106056 . 123.0 . 121.980847 . 121.016665 . 121.72738 . 118.0 . 118.0 . 119.431662 . 118.166318 . 122.352025 . 122.469351 . 119.524698 . 120.49147500000001 . 139.213399 . 138.098745 . 119.034033 . 117.07364799999999 . 138.547267 . 138.683794 . 118.0 . 118.0 . 129.622804 . 130.79626 . 118.0 . 118.107092 . 131.335093 . 129.0 . 118.011903 . 118.0 . 121.07735600000001 . 121.052016 . 118.078256 . 118.063582 . 120.418832 . 120.580984 . 126.032416 . 125.955361 . 126.01544799999999 . 125.920738 . 129.633715 . 132.895637 . 138.748307 . 139.685846 . 133.226808 . 126.220065 . 123.090215 . 124.565628 . 142.586285 . 143.719395 . 143.37634 . 139.648946 . 122.693989 . 122.676243 . 122.804818 . 122.857123 . 123.096353 . 122.815416 . 121.02064 . 121.001458 . 122.87795 . 122.847618 . 123.0 . 123.0 . 139.129291 . 137.441044 . 122.96936600000001 . 122.735328 . 123.32471 . 123.668137 . 121.895468 . 121.3928 . 118.178076 . 118.90751399999999 . 126.011928 . 125.696736 . 140.466313 . 138.44514800000002 . 124.473062 . 123.479181 . 138.39746300000002 . 137.974483 . 131.783524 . 129.681308 . 121.587743 . 121.74611300000001 . 139.569004 . 136.67933 . 122.927011 . 123.32934399999999 . 122.12632500000001 . 121.679158 . 136.673882 . 137.936044 . 122.226815 . 122.538932 . 122.307413 . 122.362877 . 122.89974000000001 . 122.997168 . 138.895069 . 140.78952900000002 . 140.654155 . 138.542937 . 125.95383 . 126.826961 . 123.803904 . 123.652435 . 120.677105 . 121.797388 . 122.719385 . 122.177099 . 123.099906 . 124.17851 . 120.924808 . 120.975973 . 121.856301 . 118.140751 . 118.0 . 118.0 . 120.206358 . 118.15287599999999 . 122.33621600000001 . 123.0 . 122.088059 . 123.0 . 120.993067 . 120.654752 . 121.624552 . 121.682636 . 118.0 . 118.0 . 118.0 . 118.0 . 119.374207 . 119.275687 . 122.956845 . 122.829681 . 122.200779 . 121.688557 . 120.803186 . 119.51532399999999 . 121.962219 . 120.534089 . 139.29266 . 137.872971 . 137.613378 . 137.47168299999998 . 118.611197 . 117.412629 . 139.12631 . 137.063599 . 141.31830200000002 . 143.726081 . 118.0 . 118.0 . 118.0 . 118.0 . 129.409825 . 128.421533 . 118.0 . 118.0 . 123.246702 . 124.481032 . 129.0 . 127.968765 . 118.024744 . 118.10682 . 121.379676 . 121.35323700000001 . 120.338815 . 120.720639 . 119.045357 . 118.945961 . 118.88061 . 119.85052400000001 . 130.200946 . 125.314589 . 137.186795 . 132.707653 . 127.562425 . 130.421596 . 126.945139 . 134.139453 . 126.225442 . 128.363149 . 127.991467 . 125.498751 . 130.605225 . 131.457413 . 124.82929 . 124.739421 . 141.0 . 127.83173 . 123.26006100000001 . 122.705772 . 124.041043 . 120.01390599999999 . 130.02019 . 125.15462 . 130.870724 . 128.712995 . 130.710511 . 129.827481 . 131.86893 . 136.542885 . 121.556361 . 123.963649 . 124.145295 . 125.2984 . 131.75538699999998 . 130.62865 . 123.45455799999999 . 123.432227 . 140.50021 . 134.576714 . 122.27696900000001 . 121.963787 . 124.001685 . 120.027764 . 128.704462 . 126.774115 . 125.539411 . 125.300208 . 131.194458 . 140.794057 . 133.55336 . 130.304203 . 130.958051 . 129.429687 . 130.52085399999999 . 130.610436 . 126.740655 . 126.680376 . 137.056193 . 128.825279 . 125.883749 . 125.486521 . 129.88302099999999 . 126.957645 . 126.490926 . 127.558801 . 122.908879 . 124.201622 . 131.689773 . 130.242597 . 131.346845 . 130.57734299999998 . 125.124595 . 125.509034 . 125.478662 . 125.100513 . 138.52364599999999 . 138.71215999999998 . 125.717522 . 132.259623 . 123.47006999999999 . 124.408805 . 124.443011 . 122.906342 . 124.007488 . 130.686701 . 120.184451 . 125.447208 . 130.002029 . 130.188303 . 124.244029 . 124.521879 . 129.721964 . 129.906575 . 137.084742 . 139.08886 . 122.65857199999999 . 122.889099 . 124.63474 . 124.920362 . 131.78384499999999 . 131.627962 . 122.97618800000001 . 122.977357 . 140.973007 . 141.0 . 121.721507 . 121.544554 . 124.00030699999999 . 124.0409 . 129.509151 . 129.246269 . 125.341399 . 125.31416300000001 . 140.366238 . 133.749594 . 132.867331 . 130.403205 . 129.687488 . 128.992809 . 130.475248 . 130.350516 . 126.684354 . 126.607478 . 133.174147 . 132.29016000000001 . 126.05010899999999 . 125.846279 . 129.620095 . 127.439056 . 128.49339700000002 . 127.474245 . 125.036269 . 124.825398 . 130.493946 . 130.607546 . 131.194323 . 131.36347 . 125.027254 . 125.058566 . 124.417552 . 124.5822 . 140.106145 . 140.174191 . 127.18687299999999 . 130.424369 . 123.141402 . 124.178638 . 122.832105 . 123.083621 . 124.079971 . 126.94778600000001 . 120.101026 . 122.789402 . 128.404332 . 130.003358 . 125.136116 . 125.139466 . 131.743821 . 130.796262 . 128.393111 . 127.93982 . 131.034092 . 130.684347 . 130.108216 . 131.347497 . 131.761799 . 130.976932 . 137.588628 . 137.99791199999999 . 121.6548 . 122.829753 . 125.015173 . 123.812795 . 123.975685 . 124.149036 . 125.06294199999999 . 125.140074 . 130.722801 . 130.916426 . 131.010302 . 130.605464 . 124.62205399999999 . 123.745833 . 123.327836 . 123.411141 . 139.825592 . 136.839761 . 133.789301 . 134.16199799999998 . 122.580038 . 122.851721 . 123.25493399999999 . 122.343204 . 124.006271 . 124.001196 . 120.156664 . 123.360307 . 128.986237 . 129.713169 . 127.39412300000001 . 124.912254 . 125.526746 . 125.5

0        111.000000
1       1090.000000
2        113.000000
3        117.000000
4        112.000000
           ...
2106     110.976842
2107     111.982942
2108     112.524036
2109     114.361936
2110     113.664709
Name: Age, Length: 2111, dtype: float64

In [545]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,111.0,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,1090.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,MayBe,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,113.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,MayBe,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,117.0,1.80,87.0,no,no,3.0,3.0,Sometimes,MayBe,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,112.0,1.78,89.8,no,no,2.0,1.0,Sometimes,MayBe,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [546]:
# applying lambda function
obesityDataSet['Age'] = obesityDataSet['Age'].apply(lambda x:x + 2)
obesityDataSet['Age']

0        113.000000
1       1092.000000
2        115.000000
3        119.000000
4        114.000000
           ...
2106     112.976842
2107     113.982942
2108     114.524036
2109     116.361936
2110     115.664709
Name: Age, Length: 2111, dtype: float64

In [555]:
# creating one more column with multiple data 
obesityDataSet['Age Category'] = obesityDataSet['Age'].apply(lambda x: "very YOUNG " if x<28 else "Not so young")

In [548]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,113.0,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Not so young
1,Female,1092.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,MayBe,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Not so young
2,Male,115.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,MayBe,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not so young
3,Male,119.0,1.80,87.0,no,no,3.0,3.0,Sometimes,MayBe,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,114.0,1.78,89.8,no,no,2.0,1.0,Sometimes,MayBe,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so young

In [549]:
obesityDataSet['Age'] = obesityDataSet['Age']/90

In [550]:
obesityDataSet.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,1.255556,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Not so young
1,Female,12.133333,1.52,56.0,yes,no,3.0,3.0,Sometimes,MayBe,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Not so young
2,Male,1.277778,1.80,77.0,yes,no,2.0,3.0,Sometimes,MayBe,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Not so young
3,Male,1.322222,1.80,87.0,no,no,3.0,3.0,Sometimes,MayBe,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so young
4,Male,1.266667,1.78,89.8,no,no,2.0,1.0,Sometimes,MayBe,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so young

In [553]:
obesityDataSet['Age'] = obesityDataSet['Age'] * 2**2

In [557]:
obesityDataSet.head(22)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,10.044444,99.00,64.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,very YOUNG
1,Female,97.066667,1.52,56.0,yes,no,3.0,3.0,Sometimes,MayBe,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Not so young
2,Male,10.222222,1.80,77.0,yes,no,2.0,3.0,Sometimes,MayBe,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,very YOUNG
3,Male,10.577778,1.80,87.0,no,no,3.0,3.0,Sometimes,MayBe,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,very YOUNG
4,Male,10.133333,1.78,89.8,no,no,2.0,1.0,Sometimes,MayBe,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very YOUNG
5,Male,10.755556,1.62,53.0,no,yes,2.0,3.0,Sometimes,Yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,very YOUNG
6,Female,10.222222,1.50,55.0,yes,yes,3.0,3.0,Sometimes,Yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,very YOUNG
7,Male,10.133333,1.64,53.0,no,no,2.0,3.0,Sometimes,Yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very YOUNG
8,Male,10.311111,1.78,64.0,yes,yes,3.0,3.0,Sometimes,Yes,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,very YOUNG
9,Male,10.133333,1.72,68.0,yes,yes,2.0,3.0,Sometimes,Yes,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,very YOUNG
10,Male,10.488889,1.85,105.0,yes,yes,3.0,3.0,Frequently,Yes,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,very YOUNG
11,Female,10.044444,1.72,80.0,yes,yes,2.0,3.0,Frequently,Yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,very YOUNG
12,Male,10.133333,1.65,56.0,no,no,3.0,3.0,Sometimes,Yes,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,very YOUNG
13,Male,11.822222,1.80,99.0,no,yes,2.0,3.0,Sometimes,Yes,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,very YOUNG
14,Male,10.222222,1.77,60.0,yes,yes,3.0,1.0,Sometimes,Yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,very YOUNG
15,Female,10.133333,1.70,66.0,yes,no,3.0,3.0,Always,Yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,very YOUNG
16,Male,10.577778,1.93,102.0,yes,yes,2.0,1.0,Sometimes,Yes,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,very YOUNG
17,Female,10.755556,1.53,78.0,no,yes,2.0,1.0,Sometimes,Yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,very YOUNG
18,Female,10.844444,1.71,82.0,yes,yes,3.0,4.0,Frequently,Yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,very YOUNG
19,Female,10.222222,1.65,70.0,yes,no,2.0,1.0,Sometimes,Yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,very YOUNG
20,Male,10.133333,1.65,80.0,yes,no,2.0,3.0,Sometimes,Yes,2.0,no,3.0,2.0,no,Walking,Overweight_Level_II,very YOUNG
21,Female,12.800000,1.69,87.0,yes,yes,3.0,1.0,Sometimes,Yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,very YOUNG